version: "3.8"

services:
  backend:
    build: .
    container_name: vitto-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://bhargavaabhishek2002_db_user:bhargavaabhishek2002_db_user@cluster0.ckefvtx.mongodb.net/SDE

    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: vitto-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: